name: 'Poetry preamble'
description: Common steps for actions that want to poetry run
inputs:
  INSTALL_ARGS:
    description: "Additional args to poetry install"
    required: false
  GHA_TOKEN:
    description: >-
      The read-only shared user GitHub token for checkout private
      repositories.
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      shell: bash
      run: $POETRY install ${{ inputs.INSTALL_ARGS }}

    - name: Allow git dependencies
      if: github.event_name != 'push'
      shell: bash
      run: >-
        git config --global
        url."https://oxionics:${{ inputs.GHA_TOKEN }}@github.com".insteadOf
        ssh://git@github.com
